FROM redis:latest

# Expose the Redis default port
EXPOSE 6379

# Default command to start Redis
CMD ["redis-server"]

# docker build -t redis:latest .

# az acr login --name acr<ENV>visitoranalytics
# docker build -t acr<ENV>visitoranalytics.azurecr.io/vtf-redis:latest .
# docker push acr<ENV>visitoranalytics.azurecr.io/vtf-redis:latest
