"""Initial migration; User

Revision ID: 46bdb2fd31bd
Revises:
Create Date: 2024-12-10 09:37:30.108786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46bdb2fd31bd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.Enum('PACIFIC_KIRITIMATI', 'PACIFIC_AUCKLAND', 'PACIFIC_CHATHAM', 'PACIFIC_FIJI', 'PACIFIC_NOUMEA', 'AUSTRALIA_SYDNEY', 'AUSTRALIA_DARWIN', 'ASIA_TOKYO', 'ASIA_KUALA_LUMPUR', 'ASIA_BANGKOK', 'ASIA_DHAKA', 'ASIA_KOLKATA', 'ASIA_TASHKENT', 'ASIA_DUBAI', 'ASIA_TEHRAN', 'EUROPE_MOSCOW', 'EUROPE_ATHENS', 'EUROPE_BERLIN', 'EUROPE_LONDON', 'ATLANTIC_AZORES', 'AMERICA_NORONHA', 'AMERICA_ARGENTINA_BUENOS_AIRES', 'AMERICA_HALIFAX', 'AMERICA_NEW_YORK', 'AMERICA_CHICAGO', 'AMERICA_DENVER', 'AMERICA_LOS_ANGELES', 'AMERICA_ANCHORAGE', 'PACIFIC_HONOLULU', 'PACIFIC_PAGO_PAGO', 'PACIFIC_MIDWAY', name='timezoneenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
